part of 'user_bloc.dart';

abstract class UserState extends Equatable {
  const UserState();

  @override
  List<Object> get props => [];
}

class UserLoading extends UserState {}

class UserLoaded extends UserState {
  UserLoaded(this.user);
  final List<Autogenerated> user;

  @override
  List<Object> get props => [user];
}

class UserError extends UserState {
  UserError(this.message);
  final String message;

  @override
  List<Object> get props => [message];
}
